import { ReactNode } from "react";
import {
  GitlabLogo,
  JiraLogo,
  ConfluenceLogo,
  GithubLogo,
  PostgresLogo,
  AWSLogo,
  AzureLogo,
  MariaDbLogo,
  UnityLogo,
  AndroidLogo,
  MUILogo,
  DockerLogo,
  CloudflareLogo,
  SolidityLogo,
  ReactLogo,
  HTMLLogo,
  CSSLogo,
  JavascriptLogo,
  TypescriptLogo,
  TerraformLogo,
  NodeLogo,
  PythonLogo,
  CSharpLogo,
  MatlabLogo,
  WindowsLogo,
  MacOSLogo,
  LinuxLogo,
  MongoDBLogo,
  ChakraUILogo,
  KubernetesLogo,
  HardhatLogo,
  VercelLogo,
  NextLogo,
} from "../components";

export const toolsServices: ReactNode[] = [
  <GitlabLogo key="gitlab" />,
  <JiraLogo key="jira" />,
  <ConfluenceLogo key="confluence" />,
  <GithubLogo key="github" />,
  <AWSLogo key="aws" />,
  <AzureLogo key="azure" />,
  <MariaDbLogo key="mariadb" />,
  <UnityLogo key="unity" />,
  <AndroidLogo key="android" />,
  <DockerLogo key="docker" />,
  <KubernetesLogo key="kubernetes" />,
  <CloudflareLogo key="cloudflare" />,
  <VercelLogo key="vercel" />,
];

export const languages: ReactNode[] = [
  <SolidityLogo key="solidity" />,
  <HardhatLogo key="hardhat" />,
  <ReactLogo key="react" />,
  <HTMLLogo key="html5" />,
  <CSSLogo key="css" />,
  <JavascriptLogo key="javascript" />,
  <TypescriptLogo key="typescript" />,
  <NextLogo key="next" />,
  <MUILogo key="mui" />,
  <ChakraUILogo key="chakra" />,
  <TerraformLogo key="terraform" />,
  <NodeLogo key="node" />,
  <CSharpLogo key="c#" />,
  <MatlabLogo key="matlab" />,
  <PostgresLogo key="postgres" />,
  <MongoDBLogo key="mongodb" />,
];

export const operatingSystems: ReactNode[] = [
  <WindowsLogo key="windows" />,
  <MacOSLogo key="macos" />,
  <LinuxLogo key="linux" />,
];
